//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve device location!.
        /// </summary>
        internal static string CantGetLocalization {
            get {
                return ResourceManager.GetString("CantGetLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t take a photo! Make sure the application has permission to take photos.
        /// </summary>
        internal static string CantTakePhoto {
            get {
                return ResourceManager.GetString("CantTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the category that best suits your report..
        /// </summary>
        internal static string CategoryMessage {
            get {
                return ResourceManager.GetString("CategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category selected!.
        /// </summary>
        internal static string CategoryNotChosen {
            get {
                return ResourceManager.GetString("CategoryNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the category that best fits your report. The categories are for illustrative purposes only, and a detailed description of your submission will be added at the end of the submission process..
        /// </summary>
        internal static string ChoseCategoryMessage {
            get {
                return ResourceManager.GetString("ChoseCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (click on this inscription to start writing).
        /// </summary>
        internal static string ClickToStartWriting {
            get {
                return ResourceManager.GetString("ClickToStartWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on location on your device.
        /// </summary>
        internal static string EnableLocalization {
            get {
                return ResourceManager.GetString("EnableLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization is disabled!.
        /// </summary>
        internal static string LocalizadionIsDisabled {
            get {
                return ResourceManager.GetString("LocalizadionIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is necessary for the acceptance of report. Make sure the location has been shared by clicking the &quot;Send Location&quot; button and agreeing to the exact location..
        /// </summary>
        internal static string LocalizationInfo {
            get {
                return ResourceManager.GetString("LocalizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is necessary to confirm your report. Make sure the application has permission to access the location.
        /// </summary>
        internal static string LocalizationIsRequired {
            get {
                return ResourceManager.GetString("LocalizationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application requires your location. Press the share location button and select the precise option..
        /// </summary>
        internal static string LocalizationMessage {
            get {
                return ResourceManager.GetString("LocalizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection!.
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your location.
        /// </summary>
        internal static string NoLocalization {
            get {
                return ResourceManager.GetString("NoLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo!.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the server! Please try again later..
        /// </summary>
        internal static string NoSerwerConnection {
            get {
                return ResourceManager.GetString("NoSerwerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) You can add a description of the report, which will help in the efficient definition of the problem and speed up its implementation. Your description cannot exceed 1000 characters..
        /// </summary>
        internal static string OptionalDescriptionMessage {
            get {
                return ResourceManager.GetString("OptionalDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a photo as it is the basis for report..
        /// </summary>
        internal static string PhotoMessage {
            get {
                return ResourceManager.GetString("PhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has not been sent!.
        /// </summary>
        internal static string ReportNotSended {
            get {
                return ResourceManager.GetString("ReportNotSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has been sent!.
        /// </summary>
        internal static string ReportSended {
            get {
                return ResourceManager.GetString("ReportSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a report.
        /// </summary>
        internal static string SendingAlert {
            get {
                return ResourceManager.GetString("SendingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share location.
        /// </summary>
        internal static string ShareLocalization {
            get {
                return ResourceManager.GetString("ShareLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo of the incident that clearly shows what the report is about. Remember to agree to use the camera to take a photo via the application..
        /// </summary>
        internal static string TakePhotoInfo {
            get {
                return ResourceManager.GetString("TakePhotoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try restarting the application.
        /// </summary>
        internal static string TryRestartApp {
            get {
                return ResourceManager.GetString("TryRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem has occurred!.
        /// </summary>
        internal static string UnsuportedErrorOccured {
            get {
                return ResourceManager.GetString("UnsuportedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
